apiVersion: v1
kind: Service
metadata:
  name: sample-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: sample-api
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: sample-ui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: sample-ui
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: {{ .Values.service.ui.port }}
